### PR TITLE
add operator_list 

### PR DESCRIPTION
**Pull request by PlugIN73**
For issue #5

### CODE REVIEW

**Comment by PlugIN73** [comment]
This will be like that:
alexander.v ALL=(root, test_user) NOPASSWD:  ALL

**Comment by franklinkim** [comment]
hi, I merged your changes but refactored a bit too:
- renamed `operator_list` to `users`
- added `hosts`
- removed `requiretty`
- added `sudo_defaults`

so if you're running the test with:

``` yaml
---

- hosts: all
  sudo: yes
  roles:
    - franklinkim.sudo
  vars:
    sudo_defaults:
      - defaults: env_reset
      - defaults: secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - name: 'user1'
        defaults: 'requiretty'
      - name: '%group1'
        defaults: '!requiretty'
    sudo_users:
      - name: 'user1'
      - name: 'user2'
        nopasswd: yes
      - name: '%group1'
        hosts: 127.0.0.1
      - name: '%group2'
        commands: '/bin/ls'
      - name: '%group3'
        users: 'user1,user2'
```

you'll end up with:

```
Defaults env_reset
Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
Defaults:user1 requiretty
Defaults:%group1 !requiretty

user1 ALL=  ALL
user2 ALL= NOPASSWD: ALL
%group1 127.0.0.1=  ALL
%group2 ALL=  /bin/ls
%group3 ALL=(user1,user2)  ALL
```

It's currently on the **develop** branch. Can you confirm that this works for you!?

**Comment by PlugIN73** [comment]
Thank you! I'll try it today later.

**Comment by PlugIN73** [comment]
@franklinkim it works for me! :+1:

**Comment by PlugIN73** [comment]
Fine! Thank you!

**Comment by franklinkim** [comment]
pleasure (y)

**Pull request merged**
